spring:
  application:
    name: market
  datasource:
    url: jdbc:mysql://localhost:3306/markety?createDatabaseIfNotExist=true
    username: COURSDB
    password: COURSDB
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
